// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwnejrxemmeayiddcpqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3bmVqcnhlbW1lYXlpZGRjcHFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTE4MDMsImV4cCI6MjA2OTEyNzgwM30.cgFEWGzNWqSlmBKrEpmmXT3D5B3HltSSUlO3pgClzM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web'
    }
  }
});

// Add debugging for auth state
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Supabase auth state change:', event, {
    user: session?.user?.id,
    hasSession: !!session,
    accessToken: session?.access_token ? 'present' : 'missing'
  });
});